#!/usr/bin/env python3
"""Regenerate launcher resources and app/build/reports/icons/launcher-preview.png.

Run: python3 tools/generate-launcher-icons.py
Requires Python 3, Pillow with WebP support, and librsvg's rsvg-convert.
The source is tools/assets/favicon.svg; no network access is needed.
"""

import io
import math
from pathlib import Path
import re
import subprocess
import xml.etree.ElementTree as ET
from xml.sax.saxutils import quoteattr

from PIL import Image, ImageChops, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "app/src/main/res"
PREVIEW = ROOT / "app/build/reports/icons/launcher-preview.png"
SVG_NS = "{http://www.w3.org/2000/svg}"
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}


def render(svg, size):
    result = subprocess.run(
        ["rsvg-convert", "--width", str(size), "--height", str(size)],
        input=svg.encode(), capture_output=True, check=True,
    )
    return Image.open(io.BytesIO(result.stdout)).convert("RGBA")


def write_resource(relative_path, content):
    target = RES / relative_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def mask_for(shape, size):
    mask = Image.new("L", (size, size))
    draw = ImageDraw.Draw(mask)
    bounds = (0, 0, size - 1, size - 1)
    if shape == "circle":
        draw.ellipse(bounds, fill=255)
    elif shape == "rounded":
        draw.rounded_rectangle(bounds, radius=size / 4, fill=255)
    elif shape == "squircle":
        points = []
        for index in range(720):
            angle = index * math.tau / 720
            x, y = math.cos(angle), math.sin(angle)
            points.append(((1 + math.copysign(abs(x) ** 0.5, x)) * (size - 1) / 2,
                           (1 + math.copysign(abs(y) ** 0.5, y)) * (size - 1) / 2))
        draw.polygon(points, fill=255)
    else:
        draw.rectangle(bounds, fill=255)
    return mask


def main():
    source = (ROOT / "tools/assets/favicon.svg").read_text(encoding="utf-8")
    svg = ET.fromstring(source)
    group = svg.find(f"{SVG_NS}g")
    # This converter intentionally supports the supplied path-only SVG, not arbitrary SVG.
    if svg.get("viewBox") != "0 0 1024 1024" or group is None or len(svg) != 1:
        raise ValueError("Expected the original 1024-square SVG with one path group")
    matrix = re.fullmatch(r"matrix\(1 0 0 1 ([\d.-]+) ([\d.-]+)\)", group.get("transform", ""))
    if matrix is None or any(path.tag != f"{SVG_NS}path" or set(path.attrib) != {"d"} for path in group):
        raise ValueError("Only translated, uniformly filled paths are supported")
    dx, dy = map(float, matrix.groups())
    color = group.attrib["fill"].upper()
    paths = [path.attrib["d"] for path in group]

    # Measure at 4x source resolution. Fit the visible art, rather than its blank canvas.
    alpha = render(source, 4096).getchannel("A")
    left, top, right, bottom = alpha.getbbox()
    cx, cy = (left + right) / 2, (top + bottom) / 2
    radius = 0
    for y in range(top, bottom):
        row = alpha.crop((left, y, right, y + 1)).getbbox()
        if row:
            radius = max(radius, math.hypot(left + row[0] - cx, y - cy),
                         math.hypot(left + row[2] - cx, y + 1 - cy))
    # 108dp adaptive canvas, at most 60dp artwork, within a 64dp safe circle.
    # Android guarantees the central 66dp circle; the extra inset protects antialiasing.
    scale = min(60 / ((bottom - top) / 4), 60 / ((right - left) / 4), 32 / (radius / 4))
    tx, ty = 54 - cx / 4 * scale, 54 - cy / 4 * scale
    scale, tx, ty = (float(f"{value:.9f}") for value in (scale, tx, ty))

    vector_paths = "\n".join(
        f'            <path android:fillColor="{color}" android:pathData={quoteattr(path)} />'
        for path in paths
    )
    write_resource("drawable/ic_launcher_foreground.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate-launcher-icons.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <group android:scaleX="{scale}" android:scaleY="{scale}"
        android:translateX="{tx}" android:translateY="{ty}">
        <group android:translateX="{dx}" android:translateY="{dy}">
{vector_paths}
        </group>
    </group>
</vector>
''')
    write_resource("drawable/ic_launcher_background.xml", '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate-launcher-icons.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="#FFFFFF" android:pathData="M0,0h108v108h-108z" />
</vector>
''')

    svg_paths = "".join(f'<path d={quoteattr(path)} />' for path in paths)
    foreground = f'<g fill="{color}" transform="translate({tx} {ty}) scale({scale})"><g transform="translate({dx} {dy})">{svg_paths}</g></g>'
    # Launcher masks reveal the central 72dp of the adaptive canvas.
    artwork = render(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72">{foreground}</svg>', 864)
    assert color == "#3085F3"
    art_alpha = artwork.getchannel("A")
    safe_mask = Image.new("L", artwork.size)
    ImageDraw.Draw(safe_mask).ellipse((36, 36, 827, 827), fill=255)
    assert ImageChops.subtract(art_alpha, safe_mask).getbbox() is None, "Logo escapes the safe zone"

    white = Image.new("RGBA", artwork.size, "white")
    base = Image.alpha_composite(white, artwork)
    for density, size in DENSITIES.items():
        directory = RES / f"mipmap-{density}"
        directory.mkdir(parents=True, exist_ok=True)
        for suffix, shape in (("", "square"), ("_round", "circle")):
            icon = base.copy()
            icon.putalpha(mask_for(shape, 864))
            icon = icon.resize((size, size), Image.Resampling.LANCZOS)
            target = directory / f"ic_launcher{suffix}.webp"
            icon.save(target, format="WEBP", lossless=True, exact=True)
            with Image.open(target) as saved:
                assert saved.size == (size, size)
                assert saved.convert("RGBA").tobytes() == icon.tobytes(), "WebP is not lossless"

    # Shape previews share the exact foreground transform used by Android.
    preview = Image.new("RGB", (1120, 360), "#E8EBF0")
    draw = ImageDraw.Draw(preview)
    font = ImageFont.load_default(size=20)
    samples = [("Square", "square"), ("Circle", "circle"),
               ("Rounded", "rounded"), ("Squircle", "squircle"), ("Themed", "circle")]
    for index, (label, shape) in enumerate(samples):
        tile = base.copy()
        if label == "Themed":
            tile = Image.new("RGBA", artwork.size, "#DCE4FF")
            tile.paste(Image.new("RGBA", artwork.size, "#25365C"), (0, 0), art_alpha)
        tile.putalpha(mask_for(shape, 864))
        tile = tile.resize((176, 176), Image.Resampling.LANCZOS)
        x = index * 224 + 24
        preview.paste(tile, (x, 64), tile)
        draw.text((x + 88, 264), label, fill="#263348", font=font, anchor="mt")
    draw.text((560, 322), "Themed colors are illustrative; the launcher chooses the palette.",
              fill="#536176", font=ImageFont.load_default(size=16), anchor="mt")
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    preview.save(PREVIEW)
    print(f"Generated 2 vectors and 10 lossless WebP icons. Preview: {PREVIEW}")


if __name__ == "__main__":
    main()
