package moe.nepnep.hduhelper.data.campuscode

import com.google.zxing.BinaryBitmap
import com.google.zxing.RGBLuminanceSource
import com.google.zxing.common.HybridBinarizer
import com.google.zxing.qrcode.QRCodeReader
import java.math.BigInteger
import java.time.Instant
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import mockwebserver3.MockResponse
import mockwebserver3.MockWebServer
import org.junit.Assert.*
import org.junit.Test

class YmtApiTest {
    @Test fun signatureMatchesPublicWebScriptWithFixedNonceAndScalar() {
        // Generated by the school's bundled sm-crypto, using synthetic input and pointPool k=1.
        val canonical = YmtSigner.canonical("/uias/authentication/index/token-h5",
            mapOf("appUrl" to "", "isCas" to "1", "isAppEnter" to "0"), "abcdef123456", Instant.parse("2026-09-06T12:00:00Z").toEpochMilli())
        assertEquals("GET\n/uias/authentication/index/token-h5\n1cd2cae232f52140b2430f718ddc22f4\nabcdef123456\nSun, 06 Sep 2026 12:00:00 GMT", canonical)
        assertEquals("eaa9210082e508b2fb8ae8877ac93a5ef3be9ab6ed6c7151a3352335347cd922555bf7006686853e444f08d63e9d7eb500ae1c829ff5df224182efd7b2b9644c", YmtSigner.sign(canonical, BigInteger.ONE))
        assertEquals("1234000", YmtSigner.qrParameters("7", 1234567).getValue("timestamp"))
    }

    @Test fun qrRoundTripPreservesCommaSuffixAndUnicode() {
        for (raw in listOf("ABCD0123456789".repeat(12) + ",12345", "synthetic-测试,+/%& 001")) {
            val qr = QrCodeEncoder.encode(raw)
            val decoded = QRCodeReader().decode(BinaryBitmap(HybridBinarizer(RGBLuminanceSource(qr.size, qr.size, qr.pixels))))
            assertArrayEquals(raw.toByteArray(Charsets.UTF_8), decoded.text.toByteArray(Charsets.UTF_8))
            assertEquals(0xffffffff.toInt(), qr.pixels.first())
            assertEquals(setOf(0xff000000.toInt(), 0xffffffff.toInt()), qr.pixels.toSet())
        }
    }

    @Test fun intervalsAndIdentityMatchWebsiteDefaults() {
        for (raw in listOf("{}", "{\"freshTime\":0}", "{\"freshTime\":-1}", "{\"freshTime\":null}"))
            assertEquals(300L, YmtApi.refreshInterval(Json.parseToJsonElement(raw).jsonObject))
        assertEquals(180L, YmtApi.refreshInterval(Json.parseToJsonElement("{\"freshTime\":180}").jsonObject))
        assertEquals("学生", YmtApi.identityName("研究生-R"))
        assertEquals("教工", YmtApi.identityName("教师优惠"))
        assertEquals("—", YmtApi.identityName("unknown"))
    }

    @Test fun casCookiesDynamicApplicationTokenAndQrRequests() = runBlocking {
        MockWebServer().use { server ->
            server.start()
            fun data(body: String) = MockResponse.Builder().body("{\"code\":200,\"data\":$body}").build()
            server.enqueue(MockResponse.Builder().addHeader("Set-Cookie", "SESSION=synthetic-cookie; Path=/; HttpOnly").body("{\"code\":200,\"data\":\"SUCCESS\"}").build())
            server.enqueue(data("{\"value\":\"synthetic-portal-token\"}"))
            server.enqueue(data("[{\"applicationName\":\"电子凭证\",\"appId\":\"dynamic-id\",\"envIp\":\"${server.url("/uias-h5/uias-app/voucher")}\"}]"))
            server.enqueue(data("{\"value\":\"synthetic-app-token\"}"))
            server.enqueue(data("{\"balance\":123.45,\"id\":7,\"userNumber\":\"test-account\",\"mainClassNames\":\"本专科生\"}"))
            server.enqueue(data("{\"name\":\"测试用户\",\"schoolClass\":\"测试学院\",\"userNumber\":\"test-account\"}"))
            server.enqueue(data("{\"freshTime\":180}"))
            server.enqueue(data("\"SYNTHETIC-QR,123\""))
            val session = YmtApi(YmtEndpoints(server.url("/"))).create()
            session.authorize("synthetic-ticket")
            val code = session.fetch("test-account")
            assertEquals("SYNTHETIC-QR,123", code.content)
            assertEquals("测试学院", code.profile.college)
            assertEquals(180L, code.refreshSeconds)
            assertEquals("123.45", code.balance)
            val requests = List(8) { server.takeRequest() }
            assertTrue(requests[0].target.contains("ticket=synthetic-ticket"))
            assertNull(requests[0].headers["Authorization"])
            assertEquals("SESSION=synthetic-cookie", requests[1].headers["Cookie"])
            assertEquals("synthetic-portal-token", requests[2].headers["Authorization"])
            assertEquals("/uias/authentication/index/token-h5?clientId=dynamic-id", requests[3].target)
            assertEquals("synthetic-app-token", requests[7].headers["Authorization"])
            assertTrue(requests[7].headers["Sign"]!!.matches(Regex("[0-9a-f]{128}")))
        }
    }

    @Test fun balanceUsesYuanAndPreservesUnavailableValues() {
        for ((raw, expected) in mapOf("0" to "0.00", "12.3" to "12.30", "\"123.45\"" to "123.45", "-2.50" to "-2.50")) {
            assertEquals(expected, YmtApi.balance(Json.parseToJsonElement("{\"balance\":$raw}").jsonObject))
        }
        for (raw in listOf("{}", "{\"balance\":null}", "{\"balance\":\"\"}", "{\"balance\":\"NaN\"}", "{\"balance\":{}}")) {
            assertNull(YmtApi.balance(Json.parseToJsonElement(raw).jsonObject))
        }
    }

    @Test fun redirectsAndForeignApplicationUrlsNeverReceiveTokens() = runBlocking {
        MockWebServer().use { server ->
            server.start()
            server.enqueue(MockResponse.Builder().code(302).addHeader("Location", "https://example.com/").build())
            try { YmtApi(YmtEndpoints(server.url("/"))).create().authorize("synthetic"); fail() }
            catch (e: CampusCodeException) { assertEquals(CampusCodeFailure.SERVICE, e.kind) }
            assertEquals(1, server.requestCount)
        }
    }
}
